package net.cn;

import com.google.common.annotations.VisibleForTesting;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import java.lang.reflect.Type;
import net.cn.w;
import net.ns.i;
import net.yz.c;

public class z {
   public final float r;
   public final float T;
   public final float d;
   public final float u;
   public final float D;
   public final float V;
   public final float v;
   public final float vp;
   public final float e;
   public final float Y;
   public final float o;
   public final float R;
   public final float Z;
   public final float vN;
   public final float vU;
   public final float t;
   public final int vW;
   public final boolean vR;
   public final boolean v1;
   public final int vL;
   public final boolean q;
   public final boolean l;
   public final boolean vv;
   public final boolean P;
   public final boolean c;
   public final boolean vD;
   public final boolean I;
   public final boolean vc;
   public final int ve;
   public final boolean J;
   public final int N;
   public final boolean h;
   public final int Q;
   public final int vF;
   public final int K;
   public final int A;
   public final int m;
   public final int F;
   public final int B;
   public final int vl;
   public final int vo;
   public final int v7;
   public final int L;
   public final int g;
   public final int vP;
   public final int k;
   public final int vB;
   public final int vV;
   public final int M;
   public final int a;
   public final int y;
   public final int U;
   public final int b;
   public final int O;
   public final int z;
   public final int vS;
   public final int s;
   public final int vM;
   public final int x;
   public final int vq;
   public final int f;
   public final int G;
   public final int p;
   public final int C;
   public final int vj;
   public final int H;
   public final int vY;
   public final int S;
   public final int vm;
   public final int vf;
   public final int X;
   public final int vt;
   public final int n;
   public final int j;
   public final int v6;
   public final int W;
   public final int E;
   public final int i;
   public final int w;

   private z(net.cn.z var1) {
      this.r = var1.Z;
      this.T = var1.Q;
      this.d = var1.NC;
      this.u = var1.N8;
      this.D = var1.Nq;
      this.V = var1.h;
      this.v = var1.P;
      this.vp = var1.S;
      this.e = var1.V;
      this.Y = var1.Y;
      this.o = var1.NG;
      this.R = var1.L;
      this.Z = var1.i;
      this.vN = var1.J;
      this.vU = var1.U;
      this.t = var1.x;
      this.vW = var1.b;
      this.vR = var1.K;
      this.v1 = var1.D;
      this.vL = var1.c;
      this.q = var1.a;
      this.l = var1.NZ;
      this.vv = var1.N2;
      this.P = var1.NJ;
      this.c = var1.w;
      this.vD = var1.E;
      this.I = var1.NE;
      this.vc = var1.B;
      this.ve = var1.e;
      this.J = var1.N9;
      this.N = var1.Nr;
      this.h = var1.g;
      this.Q = var1.ND;
      this.vF = var1.R;
      this.K = var1.r;
      this.A = var1.Nu;
      this.m = var1.t;
      this.F = var1.k;
      this.B = var1.p;
      this.vl = var1.NP;
      this.vo = var1.f;
      this.v7 = var1.NF;
      this.L = var1.G;
      this.g = var1.y;
      this.vP = var1.q;
      this.k = var1.m;
      this.vB = var1.NB;
      this.vV = var1.Np;
      this.M = var1.M;
      this.a = var1.Nt;
      this.y = var1.I;
      this.U = var1.Ne;
      this.b = var1.H;
      this.O = var1.A;
      this.z = var1.n;
      this.vS = var1.l;
      this.s = var1.C;
      this.vM = var1.d;
      this.x = var1.NL;
      this.vq = var1.N6;
      this.f = var1.Nx;
      this.G = var1.Nh;
      this.p = var1.X;
      this.C = var1.O;
      this.vj = var1.F;
      this.H = var1.W;
      this.vY = var1.N_;
      this.S = var1.NK;
      this.vm = var1.z;
      this.vf = var1.o;
      this.X = var1.j;
      this.vt = var1.T;
      this.n = var1.s;
      this.j = var1.Nw;
      this.v6 = var1.Na;
      this.W = var1.N;
      this.E = var1.NW;
      this.i = var1.Nv;
      this.w = var1.v;
   }

   public static class x {
      @VisibleForTesting
      static final Gson u = (new GsonBuilder()).registerTypeAdapter(net.cn.z.class, new net.cn.z()).create();
      public float Z = 684.412F;
      public float Q = 684.412F;
      public float NC = 512.0F;
      public float N8 = 512.0F;
      public float Nq = 200.0F;
      public float h = 200.0F;
      public float P = 0.5F;
      public float S = 80.0F;
      public float V = 160.0F;
      public float Y = 80.0F;
      public float NG = 8.5F;
      public float L = 12.0F;
      public float i = 1.0F;
      public float J;
      public float U = 1.0F;
      public float x;
      public int b = 63;
      public boolean K = true;
      public boolean D = true;
      public int c = 8;
      public boolean a = true;
      public boolean NZ = true;
      public boolean N2 = true;
      public boolean NJ = true;
      public boolean w = true;
      public boolean E = true;
      public boolean NE = true;
      public boolean B = true;
      public int e = 4;
      public boolean N9 = true;
      public int Nr = 80;
      public boolean g;
      public int ND = -1;
      public int R = 4;
      public int r = 4;
      public int Nu = 33;
      public int t = 10;
      public int k;
      public int p = 256;
      public int NP = 33;
      public int f = 8;
      public int NF;
      public int G = 256;
      public int y = 33;
      public int q = 10;
      public int m;
      public int NB = 80;
      public int Np = 33;
      public int M = 10;
      public int Nt;
      public int I = 80;
      public int Ne = 33;
      public int H = 10;
      public int A;
      public int n = 80;
      public int l = 17;
      public int C = 20;
      public int d;
      public int NL = 128;
      public int N6 = 9;
      public int Nx = 20;
      public int Nh;
      public int X = 64;
      public int O = 9;
      public int F = 2;
      public int W;
      public int N_ = 32;
      public int NK = 8;
      public int z = 8;
      public int o;
      public int j = 16;
      public int T = 8;
      public int s = 1;
      public int Nw;
      public int Na = 16;
      public int N = 7;
      public int NW = 1;
      public int Nv = 16;
      public int v = 16;

      public static net.cn.z P(String var0) {
         return var0.isEmpty()?new net.cn.z():(net.cn.z)c.b(u, var0, net.cn.z.class);
      }

      public String toString() {
         return u.toJson(this);
      }

      public x() {
         this.N();
      }

      public void N() {
         this.Z = 684.412F;
         this.Q = 684.412F;
         this.NC = 512.0F;
         this.N8 = 512.0F;
         this.Nq = 200.0F;
         this.h = 200.0F;
         this.P = 0.5F;
         this.S = 80.0F;
         this.V = 160.0F;
         this.Y = 80.0F;
         this.NG = 8.5F;
         this.L = 12.0F;
         this.i = 1.0F;
         this.J = 0.0F;
         this.U = 1.0F;
         this.x = 0.0F;
         this.b = 63;
         this.K = true;
         this.D = true;
         this.c = 8;
         this.a = true;
         this.NZ = true;
         this.N2 = true;
         this.NJ = true;
         this.w = true;
         this.E = true;
         this.NE = true;
         this.B = true;
         this.e = 4;
         this.N9 = true;
         this.Nr = 80;
         this.g = false;
         this.ND = -1;
         this.R = 4;
         this.r = 4;
         this.Nu = 33;
         this.t = 10;
         this.k = 0;
         this.p = 256;
         this.NP = 33;
         this.f = 8;
         this.NF = 0;
         this.G = 256;
         this.y = 33;
         this.q = 10;
         this.m = 0;
         this.NB = 80;
         this.Np = 33;
         this.M = 10;
         this.Nt = 0;
         this.I = 80;
         this.Ne = 33;
         this.H = 10;
         this.A = 0;
         this.n = 80;
         this.l = 17;
         this.C = 20;
         this.d = 0;
         this.NL = 128;
         this.N6 = 9;
         this.Nx = 20;
         this.Nh = 0;
         this.X = 64;
         this.O = 9;
         this.F = 2;
         this.W = 0;
         this.N_ = 32;
         this.NK = 8;
         this.z = 8;
         this.o = 0;
         this.j = 16;
         this.T = 8;
         this.s = 1;
         this.Nw = 0;
         this.Na = 16;
         this.N = 7;
         this.NW = 1;
         this.Nv = 16;
         this.v = 16;
      }

      public boolean equals(Object var1) {
         if(this == var1) {
            return true;
         } else if(this.getClass() == var1.getClass()) {
            net.cn.z var2 = (net.cn.z)var1;
            return this.H != var2.H?false:(this.n != var2.n?false:(this.A != var2.A?false:(this.Ne != var2.Ne?false:(Float.compare(var2.NG, this.NG) != 0?false:(Float.compare(var2.J, this.J) != 0?false:(Float.compare(var2.i, this.i) != 0?false:(Float.compare(var2.x, this.x) != 0?false:(Float.compare(var2.U, this.U) != 0?false:(this.R != var2.R?false:(this.C != var2.C?false:(this.NL != var2.NL?false:(this.d != var2.d?false:(this.l != var2.l?false:(Float.compare(var2.Z, this.Z) != 0?false:(Float.compare(var2.P, this.P) != 0?false:(Float.compare(var2.Nq, this.Nq) != 0?false:(Float.compare(var2.h, this.h) != 0?false:(this.s != var2.s?false:(this.Na != var2.Na?false:(this.Nw != var2.Nw?false:(this.T != var2.T?false:(this.M != var2.M?false:(this.I != var2.I?false:(this.Nt != var2.Nt?false:(this.Np != var2.Np?false:(this.t != var2.t?false:(this.p != var2.p?false:(this.k != var2.k?false:(this.Nu != var2.Nu?false:(this.c != var2.c?false:(this.ND != var2.ND?false:(this.F != var2.F?false:(this.N_ != var2.N_?false:(this.W != var2.W?false:(this.O != var2.O?false:(this.q != var2.q?false:(this.NB != var2.NB?false:(this.m != var2.m?false:(this.y != var2.y?false:(this.f != var2.f?false:(this.G != var2.G?false:(this.NF != var2.NF?false:(this.NP != var2.NP?false:(Float.compare(var2.Q, this.Q) != 0?false:(this.Nx != var2.Nx?false:(this.X != var2.X?false:(this.Nh != var2.Nh?false:(this.N6 != var2.N6?false:(this.Nv != var2.Nv?false:(this.NW != var2.NW?false:(this.N != var2.N?false:(this.v != var2.v?false:(this.Nr != var2.Nr?false:(Float.compare(var2.N8, this.N8) != 0?false:(Float.compare(var2.S, this.S) != 0?false:(Float.compare(var2.V, this.V) != 0?false:(Float.compare(var2.Y, this.Y) != 0?false:(this.z != var2.z?false:(this.j != var2.j?false:(this.o != var2.o?false:(this.NK != var2.NK?false:(this.r != var2.r?false:(this.b != var2.b?false:(Float.compare(var2.L, this.L) != 0?false:(Float.compare(var2.NC, this.NC) != 0?false:(this.K != var2.K?false:(this.D != var2.D?false:(this.N9 != var2.N9?false:(this.g != var2.g?false:(this.N2 != var2.N2?false:(this.NE != var2.NE?false:(this.a != var2.a?false:(this.NJ != var2.NJ?false:(this.w != var2.w?false:(this.E != var2.E?false:(this.NZ != var2.NZ?false:(this.B != var2.B?false:this.e == var2.e)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
         } else {
            return false;
         }
      }

      public int hashCode() {
         int var1 = w.a();
         int var2 = this.Z == 0.0F?0:Float.floatToIntBits(this.Z);
         var2 = 31 * var2 + (this.Q == 0.0F?0:Float.floatToIntBits(this.Q));
         var2 = 31 * var2 + (this.NC == 0.0F?0:Float.floatToIntBits(this.NC));
         var2 = 31 * var2 + (this.N8 == 0.0F?0:Float.floatToIntBits(this.N8));
         var2 = 31 * var2 + (this.Nq == 0.0F?0:Float.floatToIntBits(this.Nq));
         var2 = 31 * var2 + (this.h == 0.0F?0:Float.floatToIntBits(this.h));
         var2 = 31 * var2 + (this.P == 0.0F?0:Float.floatToIntBits(this.P));
         var2 = 31 * var2 + (this.S == 0.0F?0:Float.floatToIntBits(this.S));
         var2 = 31 * var2 + (this.V == 0.0F?0:Float.floatToIntBits(this.V));
         var2 = 31 * var2 + (this.Y == 0.0F?0:Float.floatToIntBits(this.Y));
         var2 = 31 * var2 + (this.NG == 0.0F?0:Float.floatToIntBits(this.NG));
         var2 = 31 * var2 + (this.L == 0.0F?0:Float.floatToIntBits(this.L));
         var2 = 31 * var2 + (this.i == 0.0F?0:Float.floatToIntBits(this.i));
         var2 = 31 * var2 + (this.J == 0.0F?0:Float.floatToIntBits(this.J));
         var2 = 31 * var2 + (this.U == 0.0F?0:Float.floatToIntBits(this.U));
         var2 = 31 * var2 + (this.x == 0.0F?0:Float.floatToIntBits(this.x));
         var2 = 31 * var2 + this.b;
         var2 = 31 * var2 + (this.K?1:0);
         var2 = 31 * var2 + (this.D?1:0);
         var2 = 31 * var2 + this.c;
         var2 = 31 * var2 + (this.a?1:0);
         var2 = 31 * var2 + (this.NZ?1:0);
         var2 = 31 * var2 + (this.N2?1:0);
         var2 = 31 * var2 + (this.NJ?1:0);
         var2 = 31 * var2 + (this.w?1:0);
         var2 = 31 * var2 + (this.E?1:0);
         var2 = 31 * var2 + (this.NE?1:0);
         var2 = 31 * var2 + (this.B?1:0);
         var2 = 31 * var2 + this.e;
         var2 = 31 * var2 + (this.N9?1:0);
         var2 = 31 * var2 + this.Nr;
         var2 = 31 * var2 + (this.g?1:0);
         var2 = 31 * var2 + this.ND;
         var2 = 31 * var2 + this.R;
         var2 = 31 * var2 + this.r;
         var2 = 31 * var2 + this.Nu;
         var2 = 31 * var2 + this.t;
         var2 = 31 * var2 + this.k;
         var2 = 31 * var2 + this.p;
         var2 = 31 * var2 + this.NP;
         var2 = 31 * var2 + this.f;
         var2 = 31 * var2 + this.NF;
         var2 = 31 * var2 + this.G;
         var2 = 31 * var2 + this.y;
         var2 = 31 * var2 + this.q;
         var2 = 31 * var2 + this.m;
         var2 = 31 * var2 + this.NB;
         var2 = 31 * var2 + this.Np;
         var2 = 31 * var2 + this.M;
         var2 = 31 * var2 + this.Nt;
         var2 = 31 * var2 + this.I;
         var2 = 31 * var2 + this.Ne;
         var2 = 31 * var2 + this.H;
         var2 = 31 * var2 + this.A;
         var2 = 31 * var2 + this.n;
         var2 = 31 * var2 + this.l;
         var2 = 31 * var2 + this.C;
         var2 = 31 * var2 + this.d;
         var2 = 31 * var2 + this.NL;
         var2 = 31 * var2 + this.N6;
         var2 = 31 * var2 + this.Nx;
         var2 = 31 * var2 + this.Nh;
         var2 = 31 * var2 + this.X;
         var2 = 31 * var2 + this.O;
         var2 = 31 * var2 + this.F;
         var2 = 31 * var2 + this.W;
         var2 = 31 * var2 + this.N_;
         var2 = 31 * var2 + this.NK;
         var2 = 31 * var2 + this.z;
         var2 = 31 * var2 + this.o;
         var2 = 31 * var2 + this.j;
         var2 = 31 * var2 + this.T;
         var2 = 31 * var2 + this.s;
         var2 = 31 * var2 + this.Nw;
         var2 = 31 * var2 + this.Na;
         var2 = 31 * var2 + this.N;
         var2 = 31 * var2 + this.NW;
         var2 = 31 * var2 + this.Nv;
         var2 = 31 * var2 + this.v;
         net.u.d.h(new net.u.d[1]);
         return var2;
      }

      public net.cn.z n() {
         return new net.cn.z(this);
      }

      private static Exception a(Exception var0) {
         return var0;
      }
   }

   public static class y implements JsonDeserializer, JsonSerializer {
      public net.cn.z G(JsonElement var1, Type var2, JsonDeserializationContext var3) throws JsonParseException {
         JsonObject var5;
         net.cn.z var6;
         label0: {
            w.S();
            var5 = var1.getAsJsonObject();
            var6 = new net.cn.z();
            var6.Z = c.A(var5, "coordinateScale", var6.Z);
            var6.Q = c.A(var5, "heightScale", var6.Q);
            var6.N8 = c.A(var5, "lowerLimitScale", var6.N8);
            var6.NC = c.A(var5, "upperLimitScale", var6.NC);
            var6.Nq = c.A(var5, "depthNoiseScaleX", var6.Nq);
            var6.h = c.A(var5, "depthNoiseScaleZ", var6.h);
            var6.P = c.A(var5, "depthNoiseScaleExponent", var6.P);
            var6.S = c.A(var5, "mainNoiseScaleX", var6.S);
            var6.V = c.A(var5, "mainNoiseScaleY", var6.V);
            var6.Y = c.A(var5, "mainNoiseScaleZ", var6.Y);
            var6.NG = c.A(var5, "baseSize", var6.NG);
            var6.L = c.A(var5, "stretchY", var6.L);
            var6.i = c.A(var5, "biomeDepthWeight", var6.i);
            var6.J = c.A(var5, "biomeDepthOffset", var6.J);
            var6.U = c.A(var5, "biomeScaleWeight", var6.U);
            var6.x = c.A(var5, "biomeScaleOffset", var6.x);
            var6.b = c.t(var5, "seaLevel", var6.b);
            var6.K = c.a(var5, "useCaves", var6.K);
            var6.D = c.a(var5, "useDungeons", var6.D);
            var6.c = c.t(var5, "dungeonChance", var6.c);
            var6.a = c.a(var5, "useStrongholds", var6.a);
            var6.NZ = c.a(var5, "useVillages", var6.NZ);
            var6.N2 = c.a(var5, "useMineShafts", var6.N2);
            var6.NJ = c.a(var5, "useTemples", var6.NJ);
            var6.w = c.a(var5, "useMonuments", var6.w);
            var6.E = c.a(var5, "useMansions", var6.E);
            var6.NE = c.a(var5, "useRavines", var6.NE);
            var6.B = c.a(var5, "useWaterLakes", var6.B);
            var6.e = c.t(var5, "waterLakeChance", var6.e);
            var6.N9 = c.a(var5, "useLavaLakes", var6.N9);
            var6.Nr = c.t(var5, "lavaLakeChance", var6.Nr);
            var6.g = c.a(var5, "useLavaOceans", var6.g);
            var6.ND = c.t(var5, "fixedBiome", var6.ND);
            if(var6.ND < 38 && var6.ND >= -1) {
               if(var6.ND < i.y(net.nb.x.l)) {
                  break label0;
               }

               var6.ND += 2;
            }

            var6.ND = -1;
         }

         var6.R = c.t(var5, "biomeSize", var6.R);
         var6.r = c.t(var5, "riverSize", var6.r);
         var6.Nu = c.t(var5, "dirtSize", var6.Nu);
         var6.t = c.t(var5, "dirtCount", var6.t);
         var6.k = c.t(var5, "dirtMinHeight", var6.k);
         var6.p = c.t(var5, "dirtMaxHeight", var6.p);
         var6.NP = c.t(var5, "gravelSize", var6.NP);
         var6.f = c.t(var5, "gravelCount", var6.f);
         var6.NF = c.t(var5, "gravelMinHeight", var6.NF);
         var6.G = c.t(var5, "gravelMaxHeight", var6.G);
         var6.y = c.t(var5, "graniteSize", var6.y);
         var6.q = c.t(var5, "graniteCount", var6.q);
         var6.m = c.t(var5, "graniteMinHeight", var6.m);
         var6.NB = c.t(var5, "graniteMaxHeight", var6.NB);
         var6.Np = c.t(var5, "dioriteSize", var6.Np);
         var6.M = c.t(var5, "dioriteCount", var6.M);
         var6.Nt = c.t(var5, "dioriteMinHeight", var6.Nt);
         var6.I = c.t(var5, "dioriteMaxHeight", var6.I);
         var6.Ne = c.t(var5, "andesiteSize", var6.Ne);
         var6.H = c.t(var5, "andesiteCount", var6.H);
         var6.A = c.t(var5, "andesiteMinHeight", var6.A);
         var6.n = c.t(var5, "andesiteMaxHeight", var6.n);
         var6.l = c.t(var5, "coalSize", var6.l);
         var6.C = c.t(var5, "coalCount", var6.C);
         var6.d = c.t(var5, "coalMinHeight", var6.d);
         var6.NL = c.t(var5, "coalMaxHeight", var6.NL);
         var6.N6 = c.t(var5, "ironSize", var6.N6);
         var6.Nx = c.t(var5, "ironCount", var6.Nx);
         var6.Nh = c.t(var5, "ironMinHeight", var6.Nh);
         var6.X = c.t(var5, "ironMaxHeight", var6.X);
         var6.O = c.t(var5, "goldSize", var6.O);
         var6.F = c.t(var5, "goldCount", var6.F);
         var6.W = c.t(var5, "goldMinHeight", var6.W);
         var6.N_ = c.t(var5, "goldMaxHeight", var6.N_);
         var6.NK = c.t(var5, "redstoneSize", var6.NK);
         var6.z = c.t(var5, "redstoneCount", var6.z);
         var6.o = c.t(var5, "redstoneMinHeight", var6.o);
         var6.j = c.t(var5, "redstoneMaxHeight", var6.j);
         var6.T = c.t(var5, "diamondSize", var6.T);
         var6.s = c.t(var5, "diamondCount", var6.s);
         var6.Nw = c.t(var5, "diamondMinHeight", var6.Nw);
         var6.Na = c.t(var5, "diamondMaxHeight", var6.Na);
         var6.N = c.t(var5, "lapisSize", var6.N);
         var6.NW = c.t(var5, "lapisCount", var6.NW);
         var6.Nv = c.t(var5, "lapisCenterHeight", var6.Nv);
         var6.v = c.t(var5, "lapisSpread", var6.v);
         return var6;
      }

      public JsonElement l(net.cn.z var1, Type var2, JsonSerializationContext var3) {
         JsonObject var4 = new JsonObject();
         var4.addProperty("coordinateScale", Float.valueOf(var1.Z));
         var4.addProperty("heightScale", Float.valueOf(var1.Q));
         var4.addProperty("lowerLimitScale", Float.valueOf(var1.N8));
         var4.addProperty("upperLimitScale", Float.valueOf(var1.NC));
         var4.addProperty("depthNoiseScaleX", Float.valueOf(var1.Nq));
         var4.addProperty("depthNoiseScaleZ", Float.valueOf(var1.h));
         var4.addProperty("depthNoiseScaleExponent", Float.valueOf(var1.P));
         var4.addProperty("mainNoiseScaleX", Float.valueOf(var1.S));
         var4.addProperty("mainNoiseScaleY", Float.valueOf(var1.V));
         var4.addProperty("mainNoiseScaleZ", Float.valueOf(var1.Y));
         var4.addProperty("baseSize", Float.valueOf(var1.NG));
         var4.addProperty("stretchY", Float.valueOf(var1.L));
         var4.addProperty("biomeDepthWeight", Float.valueOf(var1.i));
         var4.addProperty("biomeDepthOffset", Float.valueOf(var1.J));
         var4.addProperty("biomeScaleWeight", Float.valueOf(var1.U));
         var4.addProperty("biomeScaleOffset", Float.valueOf(var1.x));
         var4.addProperty("seaLevel", Integer.valueOf(var1.b));
         var4.addProperty("useCaves", Boolean.valueOf(var1.K));
         var4.addProperty("useDungeons", Boolean.valueOf(var1.D));
         var4.addProperty("dungeonChance", Integer.valueOf(var1.c));
         var4.addProperty("useStrongholds", Boolean.valueOf(var1.a));
         var4.addProperty("useVillages", Boolean.valueOf(var1.NZ));
         var4.addProperty("useMineShafts", Boolean.valueOf(var1.N2));
         var4.addProperty("useTemples", Boolean.valueOf(var1.NJ));
         var4.addProperty("useMonuments", Boolean.valueOf(var1.w));
         var4.addProperty("useMansions", Boolean.valueOf(var1.E));
         var4.addProperty("useRavines", Boolean.valueOf(var1.NE));
         var4.addProperty("useWaterLakes", Boolean.valueOf(var1.B));
         var4.addProperty("waterLakeChance", Integer.valueOf(var1.e));
         var4.addProperty("useLavaLakes", Boolean.valueOf(var1.N9));
         var4.addProperty("lavaLakeChance", Integer.valueOf(var1.Nr));
         var4.addProperty("useLavaOceans", Boolean.valueOf(var1.g));
         var4.addProperty("fixedBiome", Integer.valueOf(var1.ND));
         var4.addProperty("biomeSize", Integer.valueOf(var1.R));
         var4.addProperty("riverSize", Integer.valueOf(var1.r));
         var4.addProperty("dirtSize", Integer.valueOf(var1.Nu));
         var4.addProperty("dirtCount", Integer.valueOf(var1.t));
         var4.addProperty("dirtMinHeight", Integer.valueOf(var1.k));
         var4.addProperty("dirtMaxHeight", Integer.valueOf(var1.p));
         var4.addProperty("gravelSize", Integer.valueOf(var1.NP));
         var4.addProperty("gravelCount", Integer.valueOf(var1.f));
         var4.addProperty("gravelMinHeight", Integer.valueOf(var1.NF));
         var4.addProperty("gravelMaxHeight", Integer.valueOf(var1.G));
         var4.addProperty("graniteSize", Integer.valueOf(var1.y));
         var4.addProperty("graniteCount", Integer.valueOf(var1.q));
         var4.addProperty("graniteMinHeight", Integer.valueOf(var1.m));
         var4.addProperty("graniteMaxHeight", Integer.valueOf(var1.NB));
         var4.addProperty("dioriteSize", Integer.valueOf(var1.Np));
         var4.addProperty("dioriteCount", Integer.valueOf(var1.M));
         var4.addProperty("dioriteMinHeight", Integer.valueOf(var1.Nt));
         var4.addProperty("dioriteMaxHeight", Integer.valueOf(var1.I));
         var4.addProperty("andesiteSize", Integer.valueOf(var1.Ne));
         var4.addProperty("andesiteCount", Integer.valueOf(var1.H));
         var4.addProperty("andesiteMinHeight", Integer.valueOf(var1.A));
         var4.addProperty("andesiteMaxHeight", Integer.valueOf(var1.n));
         var4.addProperty("coalSize", Integer.valueOf(var1.l));
         var4.addProperty("coalCount", Integer.valueOf(var1.C));
         var4.addProperty("coalMinHeight", Integer.valueOf(var1.d));
         var4.addProperty("coalMaxHeight", Integer.valueOf(var1.NL));
         var4.addProperty("ironSize", Integer.valueOf(var1.N6));
         var4.addProperty("ironCount", Integer.valueOf(var1.Nx));
         var4.addProperty("ironMinHeight", Integer.valueOf(var1.Nh));
         var4.addProperty("ironMaxHeight", Integer.valueOf(var1.X));
         var4.addProperty("goldSize", Integer.valueOf(var1.O));
         var4.addProperty("goldCount", Integer.valueOf(var1.F));
         var4.addProperty("goldMinHeight", Integer.valueOf(var1.W));
         var4.addProperty("goldMaxHeight", Integer.valueOf(var1.N_));
         var4.addProperty("redstoneSize", Integer.valueOf(var1.NK));
         var4.addProperty("redstoneCount", Integer.valueOf(var1.z));
         var4.addProperty("redstoneMinHeight", Integer.valueOf(var1.o));
         var4.addProperty("redstoneMaxHeight", Integer.valueOf(var1.j));
         var4.addProperty("diamondSize", Integer.valueOf(var1.T));
         var4.addProperty("diamondCount", Integer.valueOf(var1.s));
         var4.addProperty("diamondMinHeight", Integer.valueOf(var1.Nw));
         var4.addProperty("diamondMaxHeight", Integer.valueOf(var1.Na));
         var4.addProperty("lapisSize", Integer.valueOf(var1.N));
         var4.addProperty("lapisCount", Integer.valueOf(var1.NW));
         var4.addProperty("lapisCenterHeight", Integer.valueOf(var1.Nv));
         var4.addProperty("lapisSpread", Integer.valueOf(var1.v));
         return var4;
      }

      private static Exception a(Exception var0) {
         return var0;
      }
   }
}
