package net.nb;

import com.google.common.collect.Sets;
import java.util.Set;
import javax.annotation.Nullable;
import net.y9.e;
import net.y9.g0;
import net.y9.g7;
import net.y9.g_;
import net.y9.gh;
import net.y9.gn;
import net.y9.gq;
import net.y9.gt;
import net.y9.gv;
import net.y9.gx;
import net.y9.lr;
import net.y9.lu;
import net.y9.m;
import net.y9.n;
import net.y9.p;
import net.y9.r9;
import net.y9.ra;
import net.y9.rg;
import net.y9.ri;
import net.y9.rj;
import net.y9.rp;
import net.y9.rs;
import net.y9.t;
import net.y9.y;
import net.y9.z1;
import net.y9.z6;
import net.y9.z_;
import net.y9.zi;
import net.y9.zm;
import net.y9.zn;
import net.y9.zu;
import net.y9.zx;
import net.yz.m_;

public class f {
   private static final Set ot;
   public static final net.y9.l ou;
   public static final net.y9.l oy;
   public static final rs p;
   public static final net.y9.l dl;
   public static final net.y9.l TD;
   public static final net.y9.l oN;
   public static final net.y9.l X;
   public static final net.y9.l T8;
   public static final gx dy;
   public static final g0 uM;
   public static final gx dj;
   public static final g0 TL;
   public static final ri TF;
   public static final net.y9.l D;
   public static final net.y9.l z;
   public static final net.y9.l u7;
   public static final net.y9.l oK;
   public static final net.y9.l u6;
   public static final net.y9.l ub;
   public static final gh Tu;
   public static final gh G;
   public static final net.y9.l um;
   public static final net.y9.l Tm;
   public static final net.y9.l dT;
   public static final net.y9.l Ti;
   public static final net.y9.l v;
   public static final net.y9.l ul;
   public static final net.y9.l ug;
   public static final net.y9.l uP;
   public static final net.y9.l uR;
   public static final net.y9.l dw;
   public static final ra oG;
   public static final net.y9.l o;
   public static final zu TU;
   public static final m dY;
   public static final ra TP;
   public static final rj dZ;
   public static final net.y9.l ur;
   public static final zm dK;
   public static final n dO;
   public static final n d2;
   public static final t df;
   public static final t T;
   public static final net.y9.l uW;
   public static final net.y9.l TE;
   public static final lu dn;
   public static final lu Tt;
   public static final net.y9.l E;
   public static final net.y9.l T7;
   public static final net.y9.l W;
   public static final net.y9.l T9;
   public static final net.y9.l c;
   public static final net.y9.l uZ;
   public static final rg g;
   public static final net.y9.l uw;
   public static final net.y9.l TQ;
   public static final z_ uG;
   public static final gn dv;
   public static final net.y9.l TT;
   public static final net.y9.l ud;
   public static final net.y9.l uj;
   public static final net.y9.l uN;
   public static final net.y9.l dJ;
   public static final net.y9.l uY;
   public static final net.y9.l d7;
   public static final net.y9.l uL;
   public static final r9 dc;
   public static final r9 d0;
   public static final r9 T1;
   public static final r9 b;
   public static final r9 dH;
   public static final r9 uV;
   public static final net.y9.l K;
   public static final net.y9.l uU;
   public static final net.y9.l uI;
   public static final net.y9.l l;
   public static final net.y9.l T_;
   public static final net.y9.l Td;
   public static final r9 o2;
   public static final net.y9.l dp;
   public static final net.y9.l uT;
   public static final net.y9.l r;
   public static final net.y9.l dz;
   public static final net.y9.l ut;
   public static final net.y9.l uE;
   public static final net.y9.l Tl;
   public static final net.y9.l oD;
   public static final net.y9.l V;
   public static final z6 dW;
   public static final net.y9.l uz;
   public static final gq dF;
   public static final net.y9.l ue;
   public static final net.y9.l I;
   public static final net.y9.l u4;
   public static final net.y9.l d1;
   public static final net.y9.l e;
   public static final net.y9.l TX;
   public static final net.y9.l op;
   public static final net.y9.l TS;
   public static final net.y9.l R;
   public static final net.y9.l u9;
   public static final net.y9.l Tr;
   public static final p uJ;
   public static final net.y9.l N;
   public static final net.y9.l ds;
   public static final g7 dQ;
   public static final g7 da;
   public static final net.y9.l or;
   public static final net.y9.l uX;
   public static final net.y9.l TM;
   public static final net.y9.l d;
   public static final net.y9.l Q;
   public static final net.y9.l d8;
   public static final net.y9.l L;
   public static final net.y9.l dm;
   public static final net.y9.l H;
   public static final net.y9.l TB;
   public static final net.y9.l To;
   public static final net.y9.l P;
   public static final net.y9.l u;
   public static final net.y9.l u_;
   public static final net.y9.l C;
   public static final net.y9.l q;
   public static final net.y9.l T2;
   public static final net.y9.l u8;
   public static final net.y9.l TV;
   public static final gv u2;
   public static final net.y9.l dD;
   public static final net.y9.l Tb;
   public static final net.y9.l Tx;
   public static final net.y9.l uk;
   public static final net.y9.l dP;
   public static final net.y9.l TZ;
   public static final net.y9.l uF;
   public static final zx dh;
   public static final net.y9.l TG;
   public static final net.y9.l dE;
   public static final net.y9.l Tz;
   public static final net.y9.l Ts;
   public static final net.y9.l uv;
   public static final net.y9.l F;
   public static final lu d6;
   public static final lu S;
   public static final net.y9.l TY;
   public static final net.y9.l TA;
   public static final net.y9.l m;
   public static final net.y9.l uy;
   public static final lr d5;
   public static final net.y9.l u1;
   public static final net.y9.l du;
   public static final net.y9.l TK;
   public static final net.y9.l x;
   public static final net.y9.l u5;
   public static final net.y9.l i;
   public static final z1 uB;
   public static final net.y9.l od;
   public static final net.y9.l uh;
   public static final net.y9.l a;
   public static final net.y9.l T0;
   public static final net.y9.l uo;
   public static final rp dB;
   public static final net.y9.l uc;
   public static final net.y9.l dI;
   public static final net.y9.l uS;
   public static final net.y9.l dX;
   public static final gt dA;
   public static final gt B;
   public static final zi u3;
   public static final zi k;
   public static final net.y9.l dL;
   public static final net.y9.l s;
   public static final zn uq;
   public static final net.y9.l dd;
   public static final net.y9.l y;
   public static final net.y9.l j;
   public static final net.y9.l Ta;
   public static final net.y9.l Ty;
   public static final net.y9.l dr;
   public static final net.y9.l up;
   public static final net.y9.l ow;
   public static final net.y9.l uK;
   public static final net.y9.l oY;
   public static final net.y9.l TR;
   public static final net.y9.l d4;
   public static final net.y9.l dN;
   public static final net.y9.l dG;
   public static final net.y9.l di;
   public static final y Tg;
   public static final e T5;
   public static final g_ J;
   public static final net.y9.l oT;
   public static final net.y9.l uO;
   public static final net.y9.l uf;
   public static final net.y9.l TO;
   public static final net.y9.l Tj;
   public static final net.y9.l uD;
   public static final lu d_;
   public static final lu T4;
   public static final net.y9.l dg;
   public static final net.y9.l TW;
   public static final net.y9.l Tn;
   public static final net.y9.l uA;
   public static final net.y9.l us;
   public static final net.y9.l uQ;
   public static final lu T6;
   public static final lu dM;
   public static final net.y9.l dV;
   public static final net.y9.l Tf;
   public static final net.y9.l A;
   public static final net.y9.l dU;
   public static final net.y9.l M;
   public static final net.y9.l Tc;
   public static final net.y9.l uu;
   public static final net.y9.l U;
   public static final net.y9.l TH;
   public static final net.y9.l Tq;
   public static final net.y9.l TI;
   public static final net.y9.l f;
   public static final net.y9.l ui;
   public static final net.y9.l Tv;
   public static final net.y9.l uH;
   public static final net.y9.l TC;
   public static final net.y9.l d3;
   public static final net.y9.l dq;
   public static final net.y9.l Tp;
   public static final net.y9.l Z;
   public static final net.y9.l dx;
   public static final net.y9.l dC;
   public static final net.y9.l Tw;
   public static final net.y9.l u0;
   public static final net.y9.l h;
   public static final net.y9.l t;
   public static final net.y9.l dk;
   public static final net.y9.l dt;
   public static final net.y9.l Te;
   public static final net.y9.l Th;
   public static final net.y9.l oU;
   public static final net.y9.l Y;
   public static final net.y9.l n;
   public static final net.y9.l T3;
   public static final net.y9.l ux;
   public static final net.y9.l ua;
   public static final net.y9.l uC;
   public static final net.y9.l un;
   public static final net.y9.l dS;
   public static final net.y9.l dR;
   public static final net.y9.l oA;
   public static final net.y9.l O;
   public static final net.y9.l d9;
   public static final net.y9.l TN;
   public static final net.y9.l de;
   public static final net.y9.l w;
   public static final net.y9.l db;
   public static final net.y9.l TJ;
   private static String Tk;

   @Nullable
   private static net.y9.l H(String var0) {
      net.y9.l var1 = (net.y9.l)net.y9.l.m.B(new m_(var0));
      if(!ot.add(var1)) {
         throw new IllegalStateException("Invalid Block requested: " + var0);
      } else {
         return var1;
      }
   }

   static {
      o("ifJUIc");
      if(!net.nb.z.o()) {
         throw new RuntimeException("Accessed Blocks before Bootstrap!");
      } else {
         ot = Sets.newHashSet();
         ou = H("air");
         oy = H("stone");
         p = (rs)H("grass");
         dl = H("dirt");
         TD = H("cobblestone");
         oN = H("planks");
         X = H("sapling");
         T8 = H("bedrock");
         dy = (gx)H("flowing_water");
         uM = (g0)H("water");
         dj = (gx)H("flowing_lava");
         TL = (g0)H("lava");
         TF = (ri)H("sand");
         D = H("gravel");
         z = H("gold_ore");
         u7 = H("iron_ore");
         oK = H("coal_ore");
         u6 = H("log");
         ub = H("log2");
         Tu = (gh)H("leaves");
         G = (gh)H("leaves2");
         um = H("sponge");
         Tm = H("glass");
         dT = H("lapis_ore");
         Ti = H("lapis_block");
         v = H("dispenser");
         ul = H("sandstone");
         ug = H("noteblock");
         uP = H("bed");
         uR = H("golden_rail");
         dw = H("detector_rail");
         oG = (ra)H("sticky_piston");
         o = H("web");
         TU = (zu)H("tallgrass");
         dY = (m)H("deadbush");
         TP = (ra)H("piston");
         dZ = (rj)H("piston_head");
         ur = H("wool");
         dK = (zm)H("piston_extension");
         dO = (n)H("yellow_flower");
         d2 = (n)H("red_flower");
         df = (t)H("brown_mushroom");
         T = (t)H("red_mushroom");
         uW = H("gold_block");
         TE = H("iron_block");
         dn = (lu)H("double_stone_slab");
         Tt = (lu)H("stone_slab");
         E = H("brick_block");
         T7 = H("tnt");
         W = H("bookshelf");
         T9 = H("mossy_cobblestone");
         c = H("obsidian");
         uZ = H("torch");
         g = (rg)H("fire");
         uw = H("mob_spawner");
         TQ = H("oak_stairs");
         uG = (z_)H("chest");
         dv = (gn)H("redstone_wire");
         TT = H("diamond_ore");
         ud = H("diamond_block");
         uj = H("crafting_table");
         uN = H("wheat");
         dJ = H("farmland");
         uY = H("furnace");
         d7 = H("lit_furnace");
         uL = H("standing_sign");
         dc = (r9)H("wooden_door");
         d0 = (r9)H("spruce_door");
         T1 = (r9)H("birch_door");
         b = (r9)H("jungle_door");
         dH = (r9)H("acacia_door");
         uV = (r9)H("dark_oak_door");
         K = H("ladder");
         uU = H("rail");
         uI = H("stone_stairs");
         l = H("wall_sign");
         T_ = H("lever");
         Td = H("stone_pressure_plate");
         o2 = (r9)H("iron_door");
         dp = H("wooden_pressure_plate");
         uT = H("redstone_ore");
         r = H("lit_redstone_ore");
         dz = H("unlit_redstone_torch");
         ut = H("redstone_torch");
         uE = H("stone_button");
         Tl = H("snow_layer");
         oD = H("ice");
         V = H("snow");
         dW = (z6)H("cactus");
         uz = H("clay");
         dF = (gq)H("reeds");
         ue = H("jukebox");
         I = H("fence");
         u4 = H("spruce_fence");
         d1 = H("birch_fence");
         e = H("jungle_fence");
         TX = H("dark_oak_fence");
         op = H("acacia_fence");
         TS = H("pumpkin");
         R = H("netherrack");
         u9 = H("soul_sand");
         Tr = H("glowstone");
         uJ = (p)H("portal");
         N = H("lit_pumpkin");
         ds = H("cake");
         dQ = (g7)H("unpowered_repeater");
         da = (g7)H("powered_repeater");
         or = H("trapdoor");
         uX = H("monster_egg");
         TM = H("stonebrick");
         d = H("brown_mushroom_block");
         Q = H("red_mushroom_block");
         d8 = H("iron_bars");
         L = H("glass_pane");
         dm = H("melon_block");
         H = H("pumpkin_stem");
         TB = H("melon_stem");
         To = H("vine");
         P = H("fence_gate");
         u = H("spruce_fence_gate");
         u_ = H("birch_fence_gate");
         C = H("jungle_fence_gate");
         q = H("dark_oak_fence_gate");
         T2 = H("acacia_fence_gate");
         u8 = H("brick_stairs");
         TV = H("stone_brick_stairs");
         u2 = (gv)H("mycelium");
         dD = H("waterlily");
         Tb = H("nether_brick");
         Tx = H("nether_brick_fence");
         uk = H("nether_brick_stairs");
         dP = H("nether_wart");
         TZ = H("enchanting_table");
         uF = H("brewing_stand");
         dh = (zx)H("cauldron");
         TG = H("end_portal");
         dE = H("end_portal_frame");
         Tz = H("end_stone");
         Ts = H("dragon_egg");
         uv = H("redstone_lamp");
         F = H("lit_redstone_lamp");
         d6 = (lu)H("double_wooden_slab");
         S = (lu)H("wooden_slab");
         TY = H("cocoa");
         TA = H("sandstone_stairs");
         m = H("emerald_ore");
         uy = H("ender_chest");
         d5 = (lr)H("tripwire_hook");
         u1 = H("tripwire");
         du = H("emerald_block");
         TK = H("spruce_stairs");
         x = H("birch_stairs");
         u5 = H("jungle_stairs");
         i = H("command_block");
         uB = (z1)H("beacon");
         od = H("cobblestone_wall");
         uh = H("flower_pot");
         a = H("carrots");
         T0 = H("potatoes");
         uo = H("wooden_button");
         dB = (rp)H("skull");
         uc = H("anvil");
         dI = H("trapped_chest");
         uS = H("light_weighted_pressure_plate");
         dX = H("heavy_weighted_pressure_plate");
         dA = (gt)H("unpowered_comparator");
         B = (gt)H("powered_comparator");
         u3 = (zi)H("daylight_detector");
         k = (zi)H("daylight_detector_inverted");
         dL = H("redstone_block");
         s = H("quartz_ore");
         uq = (zn)H("hopper");
         dd = H("quartz_block");
         y = H("quartz_stairs");
         j = H("activator_rail");
         Ta = H("dropper");
         Ty = H("stained_hardened_clay");
         dr = H("barrier");
         up = H("iron_trapdoor");
         ow = H("hay_block");
         uK = H("carpet");
         oY = H("hardened_clay");
         TR = H("coal_block");
         d4 = H("packed_ice");
         dN = H("acacia_stairs");
         dG = H("dark_oak_stairs");
         di = H("slime");
         Tg = (y)H("double_plant");
         T5 = (e)H("stained_glass");
         J = (g_)H("stained_glass_pane");
         oT = H("prismarine");
         uO = H("sea_lantern");
         uf = H("standing_banner");
         TO = H("wall_banner");
         Tj = H("red_sandstone");
         uD = H("red_sandstone_stairs");
         d_ = (lu)H("double_stone_slab2");
         T4 = (lu)H("stone_slab2");
         dg = H("end_rod");
         TW = H("chorus_plant");
         Tn = H("chorus_flower");
         uA = H("purpur_block");
         us = H("purpur_pillar");
         uQ = H("purpur_stairs");
         T6 = (lu)H("purpur_double_slab");
         dM = (lu)H("purpur_slab");
         dV = H("end_bricks");
         Tf = H("beetroots");
         A = H("grass_path");
         dU = H("end_gateway");
         M = H("repeating_command_block");
         Tc = H("chain_command_block");
         uu = H("frosted_ice");
         U = H("magma");
         TH = H("nether_wart_block");
         Tq = H("red_nether_brick");
         TI = H("bone_block");
         f = H("structure_void");
         ui = H("observer");
         Tv = H("white_shulker_box");
         uH = H("orange_shulker_box");
         TC = H("magenta_shulker_box");
         d3 = H("light_blue_shulker_box");
         dq = H("yellow_shulker_box");
         Tp = H("lime_shulker_box");
         Z = H("pink_shulker_box");
         dx = H("gray_shulker_box");
         dC = H("silver_shulker_box");
         Tw = H("cyan_shulker_box");
         u0 = H("purple_shulker_box");
         h = H("blue_shulker_box");
         t = H("brown_shulker_box");
         dk = H("green_shulker_box");
         dt = H("red_shulker_box");
         Te = H("black_shulker_box");
         Th = H("white_glazed_terracotta");
         oU = H("orange_glazed_terracotta");
         Y = H("magenta_glazed_terracotta");
         n = H("light_blue_glazed_terracotta");
         T3 = H("yellow_glazed_terracotta");
         ux = H("lime_glazed_terracotta");
         ua = H("pink_glazed_terracotta");
         uC = H("gray_glazed_terracotta");
         un = H("silver_glazed_terracotta");
         dS = H("cyan_glazed_terracotta");
         dR = H("purple_glazed_terracotta");
         oA = H("blue_glazed_terracotta");
         O = H("brown_glazed_terracotta");
         d9 = H("green_glazed_terracotta");
         TN = H("red_glazed_terracotta");
         de = H("black_glazed_terracotta");
         w = H("concrete");
         db = H("concrete_powder");
         TJ = H("structure_block");
         ot.clear();
      }
   }

   public static void o(String var0) {
      Tk = var0;
   }

   public static String S() {
      return Tk;
   }

   private static IllegalStateException a(IllegalStateException var0) {
      return var0;
   }
}
