package net.nb;

import net.n0.e;
import net.n0.k4;
import net.n0.r;
import net.n0.y;
import net.n0.yd;
import net.n0.yk;
import net.n0.yn;
import net.n0.yr;
import net.yz.m_;

public class j {
   public static final y SL;
   public static final y YC;
   public static final y X;
   public static final y Wv;
   public static final y YU;
   public static final y W8;
   public static final e w;
   public static final y W_;
   public static final y WT;
   public static final y l;
   public static final y u;
   public static final y B;
   public static final y S1;
   public static final y F;
   public static final y O;
   public static final y Yo;
   public static final y Sg;
   public static final y WA;
   public static final y Y7;
   public static final y S0;
   public static final y Wl;
   public static final y Wy;
   public static final y Wt;
   public static final y YA;
   public static final y WP;
   public static final y Sx;
   public static final y SY;
   public static final y Wu;
   public static final y o;
   public static final y Z;
   public static final y SP;
   public static final y SW;
   public static final y YW;
   public static final y G;
   public static final y Yd;
   public static final y YL;
   public static final y YP;
   public static final y Y8;
   public static final y Wz;
   public static final y Ye;
   public static final y WX;
   public static final y SN;
   public static final y Q;
   public static final y Sd;
   public static final y Y4;
   public static final net.n0.j Sb;
   public static final net.n0.j SE;
   public static final net.n0.j Sf;
   public static final net.n0.j E;
   public static final net.n0.j YO;
   public static final net.n0.j Wa;
   public static final net.n0.j Wd;
   public static final net.n0.j Yc;
   public static final net.n0.j j;
   public static final net.n0.j YE;
   public static final net.n0.j Y_;
   public static final net.n0.j YS;
   public static final net.n0.j y;
   public static final net.n0.j WJ;
   public static final net.n0.j WO;
   public static final net.n0.j x;
   public static final net.n0.j W;
   public static final net.n0.j WR;
   public static final net.n0.j WM;
   public static final net.n0.j p;
   public static final y YT;
   public static final y WC;
   public static final y Wh;
   public static final y Yz;
   public static final y J;
   public static final y Wj;
   public static final y s;
   public static final y WK;
   public static final y Ya;
   public static final y Yk;
   public static final y i;
   public static final y W0;
   public static final y YF;
   public static final y Wb;
   public static final y T;
   public static final y Y2;
   public static final y h;
   public static final y Y5;
   public static final y A;
   public static final y f;
   public static final y Yb;
   public static final y M;
   public static final y S;
   public static final y Yx;
   public static final y d;
   public static final y Wf;
   public static final y Yr;
   public static final y Sl;
   public static final y Yp;
   public static final y v;
   public static final y q;
   public static final y YZ;
   public static final y Yv;
   public static final y P;
   public static final y t;
   public static final y Wx;
   public static final y YV;
   public static final y W9;
   public static final yd WQ;
   public static final y Yj;
   public static final y Wo;
   public static final y YB;
   public static final y YY;
   public static final y n;
   public static final y SU;
   public static final y WE;
   public static final y WS;
   public static final y W1;
   public static final y Wr;
   public static final y Ss;
   public static final yn WN;
   public static final k4 W5;
   public static final y k;
   public static final y Y;
   public static final y Y3;
   public static final y U;
   public static final y S4;
   public static final y Y0;
   public static final y Y6;
   public static final y R;
   public static final y S8;
   public static final y S2;
   public static final y W4;
   public static final y YI;
   public static final y Wi;
   public static final y g;
   public static final y Wm;
   public static final y Ys;
   public static final y K;
   public static final y Yy;
   public static final y Ww;
   public static final y YG;
   public static final yk I;
   public static final yk YD;
   public static final yk Wg;
   public static final y SG;
   public static final y Ym;
   public static final y Wk;
   public static final y Sn;
   public static final y H;
   public static final y WI;
   public static final y Wn;
   public static final y W3;
   public static final y SV;
   public static final y YX;
   public static final y N;
   public static final y Yg;
   public static final y Yu;
   public static final y WZ;
   public static final y e;
   public static final y WL;
   public static final y SH;
   public static final y Yn;
   public static final y Wq;
   public static final y We;
   public static final y W2;
   public static final y Sy;
   public static final yr WW;
   public static final y b;
   public static final y Y9;
   public static final y WB;
   public static final y WG;
   public static final y Yf;
   public static final y Wp;
   public static final y c;
   public static final y r;
   public static final y W7;
   public static final y W6;
   public static final y Su;
   public static final y Sm;
   public static final y Sq;
   public static final r YH;
   public static final y z;
   public static final y YQ;
   public static final y Yq;
   public static final y S6;
   public static final y YR;
   public static final y V;
   public static final y a;
   public static final y YM;
   public static final y Yh;
   public static final y m;
   public static final y WH;
   public static final y WD;
   public static final y C;
   public static final y SR;
   public static final y Ws;
   public static final y Yw;
   public static final y SZ;
   public static final y Wc;
   public static final y D;
   public static final y WF;
   public static final y Yi;
   public static final y WU;
   public static final y Yl;
   public static final y SB;
   public static final y Y1;
   public static final y WV;
   public static final y WY;
   public static final y YN;
   public static final y Yt;
   public static final y YJ;
   public static final y SK;
   public static final y SI;
   public static final y YK;
   private static int L;

   private static y N(String var0) {
      y var1 = (y)y.V.B(new m_(var0));
      throw new IllegalStateException("Invalid Item requested: " + var0);
   }

   static {
      L(75);
      if(!net.nb.z.o()) {
         throw new RuntimeException("Accessed Items before Bootstrap!");
      } else {
         SL = N("air");
         YC = N("iron_shovel");
         X = N("iron_pickaxe");
         Wv = N("iron_axe");
         YU = N("flint_and_steel");
         W8 = N("apple");
         w = (e)N("bow");
         W_ = N("arrow");
         WT = N("spectral_arrow");
         l = N("tipped_arrow");
         u = N("coal");
         B = N("diamond");
         S1 = N("iron_ingot");
         F = N("gold_ingot");
         O = N("iron_sword");
         Yo = N("wooden_sword");
         Sg = N("wooden_shovel");
         WA = N("wooden_pickaxe");
         Y7 = N("wooden_axe");
         S0 = N("stone_sword");
         Wl = N("stone_shovel");
         Wy = N("stone_pickaxe");
         Wt = N("stone_axe");
         YA = N("diamond_sword");
         WP = N("diamond_shovel");
         Sx = N("diamond_pickaxe");
         SY = N("diamond_axe");
         Wu = N("stick");
         o = N("bowl");
         Z = N("mushroom_stew");
         SP = N("golden_sword");
         SW = N("golden_shovel");
         YW = N("golden_pickaxe");
         G = N("golden_axe");
         Yd = N("string");
         YL = N("feather");
         YP = N("gunpowder");
         Y8 = N("wooden_hoe");
         Wz = N("stone_hoe");
         Ye = N("iron_hoe");
         WX = N("diamond_hoe");
         SN = N("golden_hoe");
         Q = N("wheat_seeds");
         Sd = N("wheat");
         Y4 = N("bread");
         Sb = (net.n0.j)N("leather_helmet");
         SE = (net.n0.j)N("leather_chestplate");
         Sf = (net.n0.j)N("leather_leggings");
         E = (net.n0.j)N("leather_boots");
         YO = (net.n0.j)N("chainmail_helmet");
         Wa = (net.n0.j)N("chainmail_chestplate");
         Wd = (net.n0.j)N("chainmail_leggings");
         Yc = (net.n0.j)N("chainmail_boots");
         j = (net.n0.j)N("iron_helmet");
         YE = (net.n0.j)N("iron_chestplate");
         Y_ = (net.n0.j)N("iron_leggings");
         YS = (net.n0.j)N("iron_boots");
         y = (net.n0.j)N("diamond_helmet");
         WJ = (net.n0.j)N("diamond_chestplate");
         WO = (net.n0.j)N("diamond_leggings");
         x = (net.n0.j)N("diamond_boots");
         W = (net.n0.j)N("golden_helmet");
         WR = (net.n0.j)N("golden_chestplate");
         WM = (net.n0.j)N("golden_leggings");
         p = (net.n0.j)N("golden_boots");
         YT = N("flint");
         WC = N("porkchop");
         Wh = N("cooked_porkchop");
         Yz = N("painting");
         J = N("golden_apple");
         Wj = N("sign");
         s = N("wooden_door");
         WK = N("spruce_door");
         Ya = N("birch_door");
         Yk = N("jungle_door");
         i = N("acacia_door");
         W0 = N("dark_oak_door");
         YF = N("bucket");
         Wb = N("water_bucket");
         T = N("lava_bucket");
         Y2 = N("minecart");
         h = N("saddle");
         Y5 = N("iron_door");
         A = N("redstone");
         f = N("snowball");
         Yb = N("boat");
         M = N("spruce_boat");
         S = N("birch_boat");
         Yx = N("jungle_boat");
         d = N("acacia_boat");
         Wf = N("dark_oak_boat");
         Yr = N("leather");
         Sl = N("milk_bucket");
         Yp = N("brick");
         v = N("clay_ball");
         q = N("reeds");
         YZ = N("paper");
         Yv = N("book");
         P = N("slime_ball");
         t = N("chest_minecart");
         Wx = N("furnace_minecart");
         YV = N("egg");
         W9 = N("compass");
         WQ = (yd)N("fishing_rod");
         Yj = N("clock");
         Wo = N("glowstone_dust");
         YB = N("fish");
         YY = N("cooked_fish");
         n = N("dye");
         SU = N("bone");
         WE = N("sugar");
         WS = N("cake");
         W1 = N("bed");
         Wr = N("repeater");
         Ss = N("cookie");
         WN = (yn)N("filled_map");
         W5 = (k4)N("shears");
         k = N("melon");
         Y = N("pumpkin_seeds");
         Y3 = N("melon_seeds");
         U = N("beef");
         S4 = N("cooked_beef");
         Y0 = N("chicken");
         Y6 = N("cooked_chicken");
         R = N("mutton");
         S8 = N("cooked_mutton");
         S2 = N("rabbit");
         W4 = N("cooked_rabbit");
         YI = N("rabbit_stew");
         Wi = N("rabbit_foot");
         g = N("rabbit_hide");
         Wm = N("rotten_flesh");
         Ys = N("ender_pearl");
         K = N("blaze_rod");
         Yy = N("ghast_tear");
         Ww = N("gold_nugget");
         YG = N("nether_wart");
         I = (yk)N("potion");
         YD = (yk)N("splash_potion");
         Wg = (yk)N("lingering_potion");
         SG = N("glass_bottle");
         Ym = N("dragon_breath");
         Wk = N("spider_eye");
         Sn = N("fermented_spider_eye");
         H = N("blaze_powder");
         WI = N("magma_cream");
         Wn = N("brewing_stand");
         W3 = N("cauldron");
         SV = N("ender_eye");
         YX = N("speckled_melon");
         N = N("spawn_egg");
         Yg = N("experience_bottle");
         Yu = N("fire_charge");
         WZ = N("writable_book");
         e = N("written_book");
         WL = N("emerald");
         SH = N("item_frame");
         Yn = N("flower_pot");
         Wq = N("carrot");
         We = N("potato");
         W2 = N("baked_potato");
         Sy = N("poisonous_potato");
         WW = (yr)N("map");
         b = N("golden_carrot");
         Y9 = N("skull");
         WB = N("carrot_on_a_stick");
         WG = N("nether_star");
         Yf = N("pumpkin_pie");
         Wp = N("fireworks");
         c = N("firework_charge");
         r = N("enchanted_book");
         W7 = N("comparator");
         W6 = N("netherbrick");
         Su = N("quartz");
         Sm = N("tnt_minecart");
         Sq = N("hopper_minecart");
         YH = (r)N("armor_stand");
         z = N("iron_horse_armor");
         YQ = N("golden_horse_armor");
         Yq = N("diamond_horse_armor");
         S6 = N("lead");
         YR = N("name_tag");
         V = N("command_block_minecart");
         a = N("record_13");
         YM = N("record_cat");
         Yh = N("record_blocks");
         m = N("record_chirp");
         WH = N("record_far");
         WD = N("record_mall");
         C = N("record_mellohi");
         SR = N("record_stal");
         Ws = N("record_strad");
         Yw = N("record_ward");
         SZ = N("record_11");
         Wc = N("record_wait");
         D = N("prismarine_shard");
         WF = N("prismarine_crystals");
         Yi = N("banner");
         WU = N("end_crystal");
         Yl = N("shield");
         SB = N("elytra");
         Y1 = N("chorus_fruit");
         WV = N("chorus_fruit_popped");
         WY = N("beetroot_seeds");
         YN = N("beetroot");
         Yt = N("beetroot_soup");
         YJ = N("totem_of_undying");
         SK = N("shulker_shell");
         SI = N("iron_nugget");
         YK = N("knowledge_book");
      }
   }

   public static void L(int var0) {
      L = var0;
   }

   public static int M() {
      return L;
   }

   public static int V() {
      int var0 = M();
      return 115;
   }

   private static IllegalStateException a(IllegalStateException var0) {
      return var0;
   }
}
