package net.nb;

import net.yz.a;
import net.yz.m_;

public class l {
   public static final a Hi;
   public static final a og;
   public static final a MH;
   public static final a Kf;
   public static final a Hd;
   public static final a K5;
   public static final a DT;
   public static final a P;
   public static final a PA;
   public static final a CI;
   public static final a Mu;
   public static final a wf;
   public static final a DC;
   public static final a oF;
   public static final a u;
   public static final a wn;
   public static final a K6;
   public static final a D2;
   public static final a HK;
   public static final a P_;
   public static final a e;
   public static final a CT;
   public static final a y;
   public static final a o6;
   public static final a MF;
   public static final a CX;
   public static final a oY;
   public static final a Hv;
   public static final a Kk;
   public static final a w4;
   public static final a Mx;
   public static final a D_;
   public static final a K4;
   public static final a HH;
   public static final a HC;
   public static final a E;
   public static final a MZ;
   public static final a CA;
   public static final a wa;
   public static final a wB;
   public static final a Dq;
   public static final a Dr;
   public static final a PQ;
   public static final a Mz;
   public static final a M8;
   public static final a wO;
   public static final a CN;
   public static final a o9;
   public static final a Pw;
   public static final a wz;
   public static final a wx;
   public static final a Hj;
   public static final a KC;
   public static final a MO;
   public static final a Q;
   public static final a Mh;
   public static final a c;
   public static final a o0;
   public static final a M9;
   public static final a Pc;
   public static final a H5;
   public static final a wy;
   public static final a wD;
   public static final a Pq;
   public static final a o;
   public static final a Ci;
   public static final a H_;
   public static final a C2;
   public static final a MG;
   public static final a wr;
   public static final a D9;
   public static final a oC;
   public static final a wl;
   public static final a wJ;
   public static final a H1;
   public static final a DD;
   public static final a wX;
   public static final a wj;
   public static final a L;
   public static final a t;
   public static final a M2;
   public static final a Mi;
   public static final a PU;
   public static final a CC;
   public static final a wT;
   public static final a Dm;
   public static final a Ks;
   public static final a K0;
   public static final a KI;
   public static final a wt;
   public static final a K7;
   public static final a K2;
   public static final a Cp;
   public static final a PK;
   public static final a Kz;
   public static final a D5;
   public static final a Pd;
   public static final a oq;
   public static final a Cj;
   public static final a KH;
   public static final a DH;
   public static final a PG;
   public static final a oA;
   public static final a Hz;
   public static final a Mt;
   public static final a Kw;
   public static final a KE;
   public static final a W;
   public static final a wg;
   public static final a oG;
   public static final a MV;
   public static final a KN;
   public static final a C8;
   public static final a HW;
   public static final a Hl;
   public static final a Pi;
   public static final a Hn;
   public static final a Dy;
   public static final a MT;
   public static final a M3;
   public static final a Dc;
   public static final a Ha;
   public static final a ws;
   public static final a PT;
   public static final a DS;
   public static final a MX;
   public static final a q;
   public static final a PM;
   public static final a DE;
   public static final a KL;
   public static final a PC;
   public static final a CS;
   public static final a PH;
   public static final a O;
   public static final a P5;
   public static final a Ka;
   public static final a D4;
   public static final a DA;
   public static final a Dp;
   public static final a M6;
   public static final a ww;
   public static final a DM;
   public static final a oV;
   public static final a oS;
   public static final a C9;
   public static final a S;
   public static final a Cr;
   public static final a D0;
   public static final a Ce;
   public static final a Dj;
   public static final a Ca;
   public static final a Ms;
   public static final a Dv;
   public static final a Mw;
   public static final a oh;
   public static final a PY;
   public static final a PN;
   public static final a wo;
   public static final a Df;
   public static final a KP;
   public static final a Dg;
   public static final a Pb;
   public static final a Di;
   public static final a wN;
   public static final a KW;
   public static final a n;
   public static final a Mv;
   public static final a Dl;
   public static final a HZ;
   public static final a or;
   public static final a w3;
   public static final a Py;
   public static final a wM;
   public static final a Ki;
   public static final a w2;
   public static final a oX;
   public static final a HS;
   public static final a MI;
   public static final a Hb;
   public static final a oy;
   public static final a Cs;
   public static final a CP;
   public static final a MA;
   public static final a CH;
   public static final a Cy;
   public static final a oN;
   public static final a oL;
   public static final a oE;
   public static final a PR;
   public static final a oT;
   public static final a PF;
   public static final a oi;
   public static final a CW;
   public static final a Pm;
   public static final a Kl;
   public static final a M1;
   public static final a Hx;
   public static final a o3;
   public static final a ow;
   public static final a HP;
   public static final a H2;
   public static final a ox;
   public static final a HE;
   public static final a DB;
   public static final a Du;
   public static final a op;
   public static final a Ht;
   public static final a K1;
   public static final a D;
   public static final a KM;
   public static final a o_;
   public static final a Dt;
   public static final a l;
   public static final a ov;
   public static final a CE;
   public static final a C_;
   public static final a Kd;
   public static final a DV;
   public static final a os;
   public static final a H7;
   public static final a T;
   public static final a Pf;
   public static final a HQ;
   public static final a wV;
   public static final a Mk;
   public static final a Kb;
   public static final a Cn;
   public static final a KQ;
   public static final a K9;
   public static final a Pk;
   public static final a Pp;
   public static final a oM;
   public static final a oP;
   public static final a MQ;
   public static final a Cz;
   public static final a HL;
   public static final a wm;
   public static final a X;
   public static final a wp;
   public static final a Cx;
   public static final a ob;
   public static final a wR;
   public static final a MW;
   public static final a Pt;
   public static final a wq;
   public static final a o8;
   public static final a Mp;
   public static final a HG;
   public static final a ou;
   public static final a Po;
   public static final a N;
   public static final a oU;
   public static final a Mf;
   public static final a MP;
   public static final a Kq;
   public static final a Dd;
   public static final a Ma;
   public static final a PB;
   public static final a H;
   public static final a Kn;
   public static final a Hr;
   public static final a k;
   public static final a KD;
   public static final a Dx;
   public static final a Ct;
   public static final a i;
   public static final a DR;
   public static final a wI;
   public static final a wH;
   public static final a Hy;
   public static final a ME;
   public static final a C;
   public static final a DP;
   public static final a C7;
   public static final a w8;
   public static final a Mm;
   public static final a Ho;
   public static final a Kx;
   public static final a HY;
   public static final a CR;
   public static final a Hk;
   public static final a oa;
   public static final a h;
   public static final a H9;
   public static final a Cb;
   public static final a wF;
   public static final a we;
   public static final a Ds;
   public static final a Mq;
   public static final a Mb;
   public static final a Hm;
   public static final a Mr;
   public static final a Hu;
   public static final a PS;
   public static final a PE;
   public static final a Z;
   public static final a MR;
   public static final a KU;
   public static final a PI;
   public static final a HI;
   public static final a on;
   public static final a Dh;
   public static final a HU;
   public static final a Pe;
   public static final a Cu;
   public static final a Cv;
   public static final a w;
   public static final a MC;
   public static final a Do;
   public static final a Ke;
   public static final a CO;
   public static final a KX;
   public static final a Hs;
   public static final a Mo;
   public static final a o5;
   public static final a M;
   public static final a Pn;
   public static final a wS;
   public static final a P6;
   public static final a MN;
   public static final a x;
   public static final a oJ;
   public static final a oz;
   public static final a d;
   public static final a KY;
   public static final a K8;
   public static final a M4;
   public static final a Cf;
   public static final a H0;
   public static final a HD;
   public static final a HT;
   public static final a U;
   public static final a KO;
   public static final a Pg;
   public static final a wC;
   public static final a HA;
   public static final a wv;
   public static final a M5;
   public static final a D6;
   public static final a wd;
   public static final a P8;
   public static final a MM;
   public static final a KJ;
   public static final a Mn;
   public static final a Cc;
   public static final a G;
   public static final a J;
   public static final a HN;
   public static final a Hg;
   public static final a w_;
   public static final a oI;
   public static final a De;
   public static final a D1;
   public static final a ol;
   public static final a Ky;
   public static final a Pa;
   public static final a g;
   public static final a A;
   public static final a B;
   public static final a PV;
   public static final a KK;
   public static final a Kj;
   public static final a PO;
   public static final a oH;
   public static final a s;
   public static final a H4;
   public static final a DJ;
   public static final a MK;
   public static final a HF;
   public static final a j;
   public static final a Kp;
   public static final a Kc;
   public static final a Pz;
   public static final a Da;
   public static final a PL;
   public static final a PD;
   public static final a HR;
   public static final a Dw;
   public static final a Me;
   public static final a M_;
   public static final a wE;
   public static final a Cl;
   public static final a Kt;
   public static final a wc;
   public static final a KG;
   public static final a oo;
   public static final a Dz;
   public static final a z;
   public static final a Hc;
   public static final a KT;
   public static final a oj;
   public static final a M7;
   public static final a Kr;
   public static final a C5;
   public static final a wW;
   public static final a H6;
   public static final a DN;
   public static final a HX;
   public static final a CG;
   public static final a o1;
   public static final a CU;
   public static final a wb;
   public static final a oK;
   public static final a CL;
   public static final a Ko;
   public static final a w1;
   public static final a Hq;
   public static final a a;
   public static final a P1;
   public static final a PJ;
   public static final a wY;
   public static final a Km;
   public static final a ok;
   public static final a I;
   public static final a CD;
   public static final a Co;
   public static final a MS;
   public static final a HO;
   public static final a Dk;
   public static final a MU;
   public static final a Pu;
   public static final a Mc;
   public static final a oO;
   public static final a D7;
   public static final a w0;
   public static final a H3;
   public static final a K;
   public static final a o2;
   public static final a oW;
   public static final a f;
   public static final a DU;
   public static final a ot;
   public static final a wZ;
   public static final a M0;
   public static final a KV;
   public static final a My;
   public static final a wi;
   public static final a C3;
   public static final a Dn;
   public static final a DL;
   public static final a Cd;
   public static final a D3;
   public static final a Pl;
   public static final a P3;
   public static final a HM;
   public static final a KA;
   public static final a oc;
   public static final a DG;
   public static final a DY;
   public static final a Ck;
   public static final a HB;
   public static final a K_;
   public static final a CK;
   public static final a KZ;
   public static final a CV;
   public static final a Hp;
   public static final a Mg;
   public static final a Mj;
   public static final a P2;
   public static final a MJ;
   public static final a HJ;
   public static final a MB;
   public static final a CZ;
   public static final a Kv;
   public static final a H8;
   public static final a P4;
   public static final a DW;
   public static final a Ml;
   public static final a wG;
   public static final a w7;
   public static final a Ku;
   public static final a Cq;
   public static final a KS;
   public static final a DX;
   public static final a Ch;
   public static final a o7;
   public static final a wk;
   public static final a Kh;
   public static final a Cg;
   public static final a w9;
   public static final a PX;
   public static final a CF;
   public static final a wU;
   public static final a KR;
   public static final a MD;
   public static final a Hw;
   public static final a wP;
   public static final a ML;
   public static final a Pj;
   public static final a Kg;
   public static final a wu;
   public static final a o4;
   public static final a oQ;
   public static final a r;
   public static final a C1;
   public static final a PP;
   public static final a wA;
   public static final a Cw;
   public static final a b;
   public static final a DF;
   public static final a C4;
   public static final a Hh;
   public static final a C6;
   public static final a DI;
   public static final a Hf;
   public static final a wQ;
   public static final a DO;
   public static final a om;
   public static final a CY;
   public static final a D8;
   public static final a Px;
   public static final a K3;
   public static final a of;
   public static final a V;
   public static final a Y;
   public static final a KF;
   public static final a MY;
   public static final a C0;
   public static final a HV;
   public static final a He;
   public static final a DQ;
   public static final a Md;
   public static final a wL;
   public static final a od;
   public static final a KB;
   public static final a Ps;
   public static final a CB;
   public static final a CM;
   public static final a w6;
   public static final a w5;
   public static final a wh;
   public static final a oB;
   public static final a F;
   public static final a Pr;
   public static final a oZ;
   public static final a v;
   public static final a DZ;
   public static final a Db;
   public static final a Cm;
   public static final a CJ;
   public static final a oR;
   public static final a wK;
   public static final a R;
   public static final a oD;
   public static final a m;
   public static final a oe;
   public static final a p;
   public static final a CQ;
   public static final a DK;

   private static a h(String var0) {
      a var1 = (a)a.h.B(new m_(var0));
      throw new IllegalStateException("Invalid Sound requested: " + var0);
   }

   static {
      if(!net.nb.z.o()) {
         throw new RuntimeException("Accessed Sounds before Bootstrap!");
      } else {
         Hi = h("ambient.cave");
         og = h("block.anvil.break");
         MH = h("block.anvil.destroy");
         Kf = h("block.anvil.fall");
         Hd = h("block.anvil.hit");
         K5 = h("block.anvil.land");
         DT = h("block.anvil.place");
         P = h("block.anvil.step");
         PA = h("block.anvil.use");
         CI = h("entity.armorstand.break");
         Mu = h("entity.armorstand.fall");
         wf = h("entity.armorstand.hit");
         DC = h("entity.armorstand.place");
         oF = h("item.armor.equip_chain");
         u = h("item.armor.equip_diamond");
         wn = h("item.armor.equip_elytra");
         K6 = h("item.armor.equip_generic");
         D2 = h("item.armor.equip_gold");
         HK = h("item.armor.equip_iron");
         P_ = h("item.armor.equip_leather");
         e = h("entity.arrow.hit");
         CT = h("entity.arrow.hit_player");
         y = h("entity.arrow.shoot");
         o6 = h("entity.bat.ambient");
         MF = h("entity.bat.death");
         CX = h("entity.bat.hurt");
         oY = h("entity.bat.loop");
         Hv = h("entity.bat.takeoff");
         Kk = h("entity.blaze.ambient");
         w4 = h("entity.blaze.burn");
         Mx = h("entity.blaze.death");
         D_ = h("entity.blaze.hurt");
         K4 = h("entity.blaze.shoot");
         HH = h("entity.boat.paddle_land");
         HC = h("entity.boat.paddle_water");
         E = h("entity.bobber.retrieve");
         MZ = h("entity.bobber.splash");
         CA = h("entity.bobber.throw");
         wa = h("item.bottle.empty");
         wB = h("item.bottle.fill");
         Dq = h("item.bottle.fill_dragonbreath");
         Dr = h("block.brewing_stand.brew");
         PQ = h("item.bucket.empty");
         Mz = h("item.bucket.empty_lava");
         M8 = h("item.bucket.fill");
         wO = h("item.bucket.fill_lava");
         CN = h("entity.cat.ambient");
         o9 = h("entity.cat.death");
         Pw = h("entity.cat.hiss");
         wz = h("entity.cat.hurt");
         wx = h("entity.cat.purr");
         Hj = h("entity.cat.purreow");
         KC = h("block.chest.close");
         MO = h("block.chest.locked");
         Q = h("block.chest.open");
         Mh = h("entity.chicken.ambient");
         c = h("entity.chicken.death");
         o0 = h("entity.chicken.egg");
         M9 = h("entity.chicken.hurt");
         Pc = h("entity.chicken.step");
         H5 = h("block.chorus_flower.death");
         wy = h("block.chorus_flower.grow");
         wD = h("item.chorus_fruit.teleport");
         Pq = h("block.cloth.break");
         o = h("block.cloth.fall");
         Ci = h("block.cloth.hit");
         H_ = h("block.cloth.place");
         C2 = h("block.cloth.step");
         MG = h("block.comparator.click");
         wr = h("entity.cow.ambient");
         D9 = h("entity.cow.death");
         oC = h("entity.cow.hurt");
         wl = h("entity.cow.milk");
         wJ = h("entity.cow.step");
         H1 = h("entity.creeper.death");
         DD = h("entity.creeper.hurt");
         wX = h("entity.creeper.primed");
         wj = h("block.dispenser.dispense");
         L = h("block.dispenser.fail");
         t = h("block.dispenser.launch");
         M2 = h("entity.donkey.ambient");
         Mi = h("entity.donkey.angry");
         PU = h("entity.donkey.chest");
         CC = h("entity.donkey.death");
         wT = h("entity.donkey.hurt");
         Dm = h("entity.egg.throw");
         Ks = h("entity.elder_guardian.ambient");
         K0 = h("entity.elder_guardian.ambient_land");
         KI = h("entity.elder_guardian.curse");
         wt = h("entity.elder_guardian.death");
         K7 = h("entity.elder_guardian.death_land");
         K2 = h("entity.elder_guardian.flop");
         Cp = h("entity.elder_guardian.hurt");
         PK = h("entity.elder_guardian.hurt_land");
         Kz = h("item.elytra.flying");
         D5 = h("block.enchantment_table.use");
         Pd = h("block.enderchest.close");
         oq = h("block.enderchest.open");
         Cj = h("entity.enderdragon.ambient");
         KH = h("entity.enderdragon.death");
         DH = h("entity.enderdragon_fireball.explode");
         PG = h("entity.enderdragon.flap");
         oA = h("entity.enderdragon.growl");
         Hz = h("entity.enderdragon.hurt");
         Mt = h("entity.enderdragon.shoot");
         Kw = h("entity.endereye.death");
         KE = h("entity.endereye.launch");
         W = h("entity.endermen.ambient");
         wg = h("entity.endermen.death");
         oG = h("entity.endermen.hurt");
         MV = h("entity.endermen.scream");
         KN = h("entity.endermen.stare");
         C8 = h("entity.endermen.teleport");
         HW = h("entity.endermite.ambient");
         Hl = h("entity.endermite.death");
         Pi = h("entity.endermite.hurt");
         Hn = h("entity.endermite.step");
         Dy = h("entity.enderpearl.throw");
         MT = h("block.end_gateway.spawn");
         M3 = h("block.end_portal_frame.fill");
         Dc = h("block.end_portal.spawn");
         Ha = h("entity.evocation_fangs.attack");
         ws = h("entity.evocation_illager.ambient");
         PT = h("entity.evocation_illager.cast_spell");
         DS = h("entity.evocation_illager.death");
         MX = h("entity.evocation_illager.hurt");
         q = h("entity.evocation_illager.prepare_attack");
         PM = h("entity.evocation_illager.prepare_summon");
         DE = h("entity.evocation_illager.prepare_wololo");
         KL = h("entity.experience_bottle.throw");
         PC = h("entity.experience_orb.pickup");
         CS = h("block.fence_gate.close");
         PH = h("block.fence_gate.open");
         O = h("item.firecharge.use");
         P5 = h("entity.firework.blast");
         Ka = h("entity.firework.blast_far");
         D4 = h("entity.firework.large_blast");
         DA = h("entity.firework.large_blast_far");
         Dp = h("entity.firework.launch");
         M6 = h("entity.firework.shoot");
         ww = h("entity.firework.twinkle");
         DM = h("entity.firework.twinkle_far");
         oV = h("block.fire.ambient");
         oS = h("block.fire.extinguish");
         C9 = h("item.flintandsteel.use");
         S = h("block.furnace.fire_crackle");
         Cr = h("entity.generic.big_fall");
         D0 = h("entity.generic.burn");
         Ce = h("entity.generic.death");
         Dj = h("entity.generic.drink");
         Ca = h("entity.generic.eat");
         Ms = h("entity.generic.explode");
         Dv = h("entity.generic.extinguish_fire");
         Mw = h("entity.generic.hurt");
         oh = h("entity.generic.small_fall");
         PY = h("entity.generic.splash");
         PN = h("entity.generic.swim");
         wo = h("entity.ghast.ambient");
         Df = h("entity.ghast.death");
         KP = h("entity.ghast.hurt");
         Dg = h("entity.ghast.scream");
         Pb = h("entity.ghast.shoot");
         Di = h("entity.ghast.warn");
         wN = h("block.glass.break");
         KW = h("block.glass.fall");
         n = h("block.glass.hit");
         Mv = h("block.glass.place");
         Dl = h("block.glass.step");
         HZ = h("block.grass.break");
         or = h("block.grass.fall");
         w3 = h("block.grass.hit");
         Py = h("block.grass.place");
         wM = h("block.grass.step");
         Ki = h("block.gravel.break");
         w2 = h("block.gravel.fall");
         oX = h("block.gravel.hit");
         HS = h("block.gravel.place");
         MI = h("block.gravel.step");
         Hb = h("entity.guardian.ambient");
         oy = h("entity.guardian.ambient_land");
         Cs = h("entity.guardian.attack");
         CP = h("entity.guardian.death");
         MA = h("entity.guardian.death_land");
         CH = h("entity.guardian.flop");
         Cy = h("entity.guardian.hurt");
         oN = h("entity.guardian.hurt_land");
         oL = h("item.hoe.till");
         oE = h("entity.horse.ambient");
         PR = h("entity.horse.angry");
         oT = h("entity.horse.armor");
         PF = h("entity.horse.breathe");
         oi = h("entity.horse.death");
         CW = h("entity.horse.eat");
         Pm = h("entity.horse.gallop");
         Kl = h("entity.horse.hurt");
         M1 = h("entity.horse.jump");
         Hx = h("entity.horse.land");
         o3 = h("entity.horse.saddle");
         ow = h("entity.horse.step");
         HP = h("entity.horse.step_wood");
         H2 = h("entity.hostile.big_fall");
         ox = h("entity.hostile.death");
         HE = h("entity.hostile.hurt");
         DB = h("entity.hostile.small_fall");
         Du = h("entity.hostile.splash");
         op = h("entity.hostile.swim");
         Ht = h("entity.husk.ambient");
         K1 = h("entity.husk.death");
         D = h("entity.husk.hurt");
         KM = h("entity.husk.step");
         o_ = h("entity.illusion_illager.ambient");
         Dt = h("entity.illusion_illager.cast_spell");
         l = h("entity.illusion_illager.death");
         ov = h("entity.illusion_illager.hurt");
         CE = h("entity.illusion_illager.mirror_move");
         C_ = h("entity.illusion_illager.prepare_blindness");
         Kd = h("entity.illusion_illager.prepare_mirror");
         DV = h("entity.irongolem.attack");
         os = h("entity.irongolem.death");
         H7 = h("entity.irongolem.hurt");
         T = h("entity.irongolem.step");
         Pf = h("block.iron_door.close");
         HQ = h("block.iron_door.open");
         wV = h("block.iron_trapdoor.close");
         Mk = h("block.iron_trapdoor.open");
         Kb = h("entity.itemframe.add_item");
         Cn = h("entity.itemframe.break");
         KQ = h("entity.itemframe.place");
         K9 = h("entity.itemframe.remove_item");
         Pk = h("entity.itemframe.rotate_item");
         Pp = h("entity.item.break");
         oM = h("entity.item.pickup");
         oP = h("block.ladder.break");
         MQ = h("block.ladder.fall");
         Cz = h("block.ladder.hit");
         HL = h("block.ladder.place");
         wm = h("block.ladder.step");
         X = h("block.lava.ambient");
         wp = h("block.lava.extinguish");
         Cx = h("block.lava.pop");
         ob = h("entity.leashknot.break");
         wR = h("entity.leashknot.place");
         MW = h("block.lever.click");
         Pt = h("entity.lightning.impact");
         wq = h("entity.lightning.thunder");
         o8 = h("entity.lingeringpotion.throw");
         Mp = h("entity.llama.ambient");
         HG = h("entity.llama.angry");
         ou = h("entity.llama.chest");
         Po = h("entity.llama.death");
         N = h("entity.llama.eat");
         oU = h("entity.llama.hurt");
         Mf = h("entity.llama.spit");
         MP = h("entity.llama.step");
         Kq = h("entity.llama.swag");
         Dd = h("entity.magmacube.death");
         Ma = h("entity.magmacube.hurt");
         PB = h("entity.magmacube.jump");
         H = h("entity.magmacube.squish");
         Kn = h("block.metal.break");
         Hr = h("block.metal.fall");
         k = h("block.metal.hit");
         KD = h("block.metal.place");
         Dx = h("block.metal_pressureplate.click_off");
         Ct = h("block.metal_pressureplate.click_on");
         i = h("block.metal.step");
         DR = h("entity.minecart.inside");
         wI = h("entity.minecart.riding");
         wH = h("entity.mooshroom.shear");
         Hy = h("entity.mule.ambient");
         ME = h("entity.mule.chest");
         C = h("entity.mule.death");
         DP = h("entity.mule.hurt");
         C7 = h("music.creative");
         w8 = h("music.credits");
         Mm = h("music.dragon");
         Ho = h("music.end");
         Kx = h("music.game");
         HY = h("music.menu");
         CR = h("music.nether");
         Hk = h("block.note.basedrum");
         oa = h("block.note.bass");
         h = h("block.note.bell");
         H9 = h("block.note.chime");
         Cb = h("block.note.flute");
         wF = h("block.note.guitar");
         we = h("block.note.harp");
         Ds = h("block.note.hat");
         Mq = h("block.note.pling");
         Mb = h("block.note.snare");
         Hm = h("block.note.xylophone");
         Mr = h("entity.painting.break");
         Hu = h("entity.painting.place");
         PS = h("entity.parrot.ambient");
         PE = h("entity.parrot.death");
         Z = h("entity.parrot.eat");
         MR = h("entity.parrot.fly");
         KU = h("entity.parrot.hurt");
         PI = h("entity.parrot.imitate.blaze");
         HI = h("entity.parrot.imitate.creeper");
         on = h("entity.parrot.imitate.elder_guardian");
         Dh = h("entity.parrot.imitate.enderdragon");
         HU = h("entity.parrot.imitate.enderman");
         Pe = h("entity.parrot.imitate.endermite");
         Cu = h("entity.parrot.imitate.evocation_illager");
         Cv = h("entity.parrot.imitate.ghast");
         w = h("entity.parrot.imitate.husk");
         MC = h("entity.parrot.imitate.illusion_illager");
         Do = h("entity.parrot.imitate.magmacube");
         Ke = h("entity.parrot.imitate.polar_bear");
         CO = h("entity.parrot.imitate.shulker");
         KX = h("entity.parrot.imitate.silverfish");
         Hs = h("entity.parrot.imitate.skeleton");
         Mo = h("entity.parrot.imitate.slime");
         o5 = h("entity.parrot.imitate.spider");
         M = h("entity.parrot.imitate.stray");
         Pn = h("entity.parrot.imitate.vex");
         wS = h("entity.parrot.imitate.vindication_illager");
         P6 = h("entity.parrot.imitate.witch");
         MN = h("entity.parrot.imitate.wither");
         x = h("entity.parrot.imitate.wither_skeleton");
         oJ = h("entity.parrot.imitate.wolf");
         oz = h("entity.parrot.imitate.zombie");
         d = h("entity.parrot.imitate.zombie_pigman");
         KY = h("entity.parrot.imitate.zombie_villager");
         K8 = h("entity.parrot.step");
         M4 = h("entity.pig.ambient");
         Cf = h("entity.pig.death");
         H0 = h("entity.pig.hurt");
         HD = h("entity.pig.saddle");
         HT = h("entity.pig.step");
         U = h("block.piston.contract");
         KO = h("block.piston.extend");
         Pg = h("entity.player.attack.crit");
         wC = h("entity.player.attack.knockback");
         HA = h("entity.player.attack.nodamage");
         wv = h("entity.player.attack.strong");
         M5 = h("entity.player.attack.sweep");
         D6 = h("entity.player.attack.weak");
         wd = h("entity.player.big_fall");
         P8 = h("entity.player.breath");
         MM = h("entity.player.burp");
         KJ = h("entity.player.death");
         Mn = h("entity.player.hurt");
         Cc = h("entity.player.hurt_drown");
         G = h("entity.player.hurt_on_fire");
         J = h("entity.player.levelup");
         HN = h("entity.player.small_fall");
         Hg = h("entity.player.splash");
         w_ = h("entity.player.swim");
         oI = h("entity.polar_bear.ambient");
         De = h("entity.polar_bear.baby_ambient");
         D1 = h("entity.polar_bear.death");
         ol = h("entity.polar_bear.hurt");
         Ky = h("entity.polar_bear.step");
         Pa = h("entity.polar_bear.warning");
         g = h("block.portal.ambient");
         A = h("block.portal.travel");
         B = h("block.portal.trigger");
         PV = h("entity.rabbit.ambient");
         KK = h("entity.rabbit.attack");
         Kj = h("entity.rabbit.death");
         PO = h("entity.rabbit.hurt");
         oH = h("entity.rabbit.jump");
         s = h("record.11");
         H4 = h("record.13");
         DJ = h("record.blocks");
         MK = h("record.cat");
         HF = h("record.chirp");
         j = h("record.far");
         Kp = h("record.mall");
         Kc = h("record.mellohi");
         Pz = h("record.stal");
         Da = h("record.strad");
         PL = h("record.wait");
         PD = h("record.ward");
         HR = h("block.redstone_torch.burnout");
         Dw = h("block.sand.break");
         Me = h("block.sand.fall");
         M_ = h("block.sand.hit");
         wE = h("block.sand.place");
         Cl = h("block.sand.step");
         Kt = h("entity.sheep.ambient");
         wc = h("entity.sheep.death");
         KG = h("entity.sheep.hurt");
         oo = h("entity.sheep.shear");
         Dz = h("entity.sheep.step");
         z = h("item.shield.block");
         Hc = h("item.shield.break");
         KT = h("item.shovel.flatten");
         oj = h("entity.shulker.ambient");
         M7 = h("block.shulker_box.close");
         Kr = h("block.shulker_box.open");
         C5 = h("entity.shulker_bullet.hit");
         wW = h("entity.shulker_bullet.hurt");
         H6 = h("entity.shulker.close");
         DN = h("entity.shulker.death");
         HX = h("entity.shulker.hurt");
         CG = h("entity.shulker.hurt_closed");
         o1 = h("entity.shulker.open");
         CU = h("entity.shulker.shoot");
         wb = h("entity.shulker.teleport");
         oK = h("entity.silverfish.ambient");
         CL = h("entity.silverfish.death");
         Ko = h("entity.silverfish.hurt");
         w1 = h("entity.silverfish.step");
         Hq = h("entity.skeleton.ambient");
         a = h("entity.skeleton.death");
         P1 = h("entity.skeleton_horse.ambient");
         PJ = h("entity.skeleton_horse.death");
         wY = h("entity.skeleton_horse.hurt");
         Km = h("entity.skeleton.hurt");
         ok = h("entity.skeleton.shoot");
         I = h("entity.skeleton.step");
         CD = h("entity.slime.attack");
         Co = h("block.slime.break");
         MS = h("entity.slime.death");
         HO = h("block.slime.fall");
         Dk = h("block.slime.hit");
         MU = h("entity.slime.hurt");
         Pu = h("entity.slime.jump");
         Mc = h("block.slime.place");
         oO = h("entity.slime.squish");
         D7 = h("block.slime.step");
         w0 = h("entity.small_magmacube.death");
         H3 = h("entity.small_magmacube.hurt");
         K = h("entity.small_magmacube.squish");
         o2 = h("entity.small_slime.death");
         oW = h("entity.small_slime.hurt");
         f = h("entity.small_slime.jump");
         DU = h("entity.small_slime.squish");
         ot = h("entity.snowball.throw");
         wZ = h("entity.snowman.ambient");
         M0 = h("entity.snowman.death");
         KV = h("entity.snowman.hurt");
         My = h("entity.snowman.shoot");
         wi = h("block.snow.break");
         C3 = h("block.snow.fall");
         Dn = h("block.snow.hit");
         DL = h("block.snow.place");
         Cd = h("block.snow.step");
         D3 = h("entity.spider.ambient");
         Pl = h("entity.spider.death");
         P3 = h("entity.spider.hurt");
         HM = h("entity.spider.step");
         KA = h("entity.splash_potion.break");
         oc = h("entity.splash_potion.throw");
         DG = h("entity.squid.ambient");
         DY = h("entity.squid.death");
         Ck = h("entity.squid.hurt");
         HB = h("block.stone.break");
         K_ = h("block.stone_button.click_off");
         CK = h("block.stone_button.click_on");
         KZ = h("block.stone.fall");
         CV = h("block.stone.hit");
         Hp = h("block.stone.place");
         Mg = h("block.stone_pressureplate.click_off");
         Mj = h("block.stone_pressureplate.click_on");
         P2 = h("block.stone.step");
         MJ = h("entity.stray.ambient");
         HJ = h("entity.stray.death");
         MB = h("entity.stray.hurt");
         CZ = h("entity.stray.step");
         Kv = h("enchant.thorns.hit");
         H8 = h("entity.tnt.primed");
         P4 = h("item.totem.use");
         DW = h("block.tripwire.attach");
         Ml = h("block.tripwire.click_off");
         wG = h("block.tripwire.click_on");
         w7 = h("block.tripwire.detach");
         Ku = h("ui.button.click");
         Cq = h("ui.toast.in");
         KS = h("ui.toast.out");
         DX = h("ui.toast.challenge_complete");
         Ch = h("entity.vex.ambient");
         o7 = h("entity.vex.charge");
         wk = h("entity.vex.death");
         Kh = h("entity.vex.hurt");
         Cg = h("entity.villager.ambient");
         w9 = h("entity.villager.death");
         PX = h("entity.villager.hurt");
         CF = h("entity.villager.no");
         wU = h("entity.villager.trading");
         KR = h("entity.villager.yes");
         MD = h("entity.vindication_illager.ambient");
         Hw = h("entity.vindication_illager.death");
         wP = h("entity.vindication_illager.hurt");
         ML = h("block.waterlily.place");
         Pj = h("block.water.ambient");
         Kg = h("weather.rain");
         wu = h("weather.rain.above");
         o4 = h("entity.witch.ambient");
         oQ = h("entity.witch.death");
         r = h("entity.witch.drink");
         C1 = h("entity.witch.hurt");
         PP = h("entity.witch.throw");
         wA = h("entity.wither.ambient");
         Cw = h("entity.wither.break_block");
         b = h("entity.wither.death");
         DF = h("entity.wither.hurt");
         C4 = h("entity.wither.shoot");
         Hh = h("entity.wither_skeleton.ambient");
         C6 = h("entity.wither_skeleton.death");
         DI = h("entity.wither_skeleton.hurt");
         Hf = h("entity.wither_skeleton.step");
         wQ = h("entity.wither.spawn");
         DO = h("entity.wolf.ambient");
         om = h("entity.wolf.death");
         CY = h("entity.wolf.growl");
         D8 = h("entity.wolf.howl");
         Px = h("entity.wolf.hurt");
         K3 = h("entity.wolf.pant");
         of = h("entity.wolf.shake");
         V = h("entity.wolf.step");
         Y = h("entity.wolf.whine");
         KF = h("block.wooden_door.close");
         MY = h("block.wooden_door.open");
         C0 = h("block.wooden_trapdoor.close");
         HV = h("block.wooden_trapdoor.open");
         He = h("block.wood.break");
         DQ = h("block.wood_button.click_off");
         Md = h("block.wood_button.click_on");
         wL = h("block.wood.fall");
         od = h("block.wood.hit");
         KB = h("block.wood.place");
         Ps = h("block.wood_pressureplate.click_off");
         CB = h("block.wood_pressureplate.click_on");
         CM = h("block.wood.step");
         w6 = h("entity.zombie.ambient");
         w5 = h("entity.zombie.attack_door_wood");
         wh = h("entity.zombie.attack_iron_door");
         oB = h("entity.zombie.break_door_wood");
         F = h("entity.zombie.death");
         Pr = h("entity.zombie_horse.ambient");
         oZ = h("entity.zombie_horse.death");
         v = h("entity.zombie_horse.hurt");
         DZ = h("entity.zombie.hurt");
         Db = h("entity.zombie.infect");
         Cm = h("entity.zombie_pig.ambient");
         CJ = h("entity.zombie_pig.angry");
         oR = h("entity.zombie_pig.death");
         wK = h("entity.zombie_pig.hurt");
         R = h("entity.zombie.step");
         oD = h("entity.zombie_villager.ambient");
         m = h("entity.zombie_villager.converted");
         oe = h("entity.zombie_villager.cure");
         p = h("entity.zombie_villager.death");
         CQ = h("entity.zombie_villager.hurt");
         DK = h("entity.zombie_villager.step");
      }
   }

   private static IllegalStateException a(IllegalStateException var0) {
      return var0;
   }
}
